In [1]:
from src.pricing import reload_prices_df

prices = reload_prices_df()
prices.head()

shape: (5, 6)
┌────────────────┬───────────┬─────┬───────┬─────────────┬────────────────────────────────┐
│ location       ┆ lmp       ┆ mcc ┆ mlc   ┆ status_code ┆ datetime                       │
│ ---            ┆ ---       ┆ --- ┆ ---   ┆ ---         ┆ ---                            │
│ str            ┆ f32       ┆ f32 ┆ f32   ┆ i16         ┆ datetime[μs, America/Chicago]  │
╞════════════════╪═══════════╪═════╪═══════╪═════════════╪════════════════════════════════╡
│ AECI           ┆ 28.26     ┆ 0.0 ┆ -1.86 ┆ 200         ┆ 2026-01-05 19:49:01.563255 CST │
│ ALTE.1ROCKGEN  ┆ 28.469999 ┆ 0.0 ┆ -1.65 ┆ 200         ┆ 2026-01-05 19:49:01.563255 CST │
│ ALTE.COLUMBAL1 ┆ 29.190001 ┆ 0.0 ┆ -0.93 ┆ 200         ┆ 2026-01-05 19:49:01.563255 CST │
│ ALTE.COLUMBAL2 ┆ 29.07     ┆ 0.0 ┆ -1.05 ┆ 200         ┆ 2026-01-05 19:49:01.563255 CST │
│ ALTE.EDGG5G5   ┆ 29.469999 ┆ 0.0 ┆ -0.65 ┆ 200         ┆ 2026-01-05 19:49:01.563255 CST │
└────────────────┴───────────┴─────┴───────┴─────────────┴────────────────────────────────┘

In [2]:
from src.location import get_location_df

locations = get_location_df()
locations.head()

shape: (5, 5)
┌────────────────┬───────────┬─────────┬──────────┬───────────┐
│ location       ┆ node_type ┆ region  ┆ latitude ┆ longitude │
│ ---            ┆ ---       ┆ ---     ┆ ---      ┆ ---       │
│ str            ┆ str       ┆ str     ┆ f64      ┆ f64       │
╞════════════════╪═══════════╪═════════╪══════════╪═══════════╡
│ AECI           ┆ INT       ┆ Midwest ┆ -92.6024 ┆ 39.4467   │
│ ALTE.1ROCKGEN  ┆ GEN       ┆ Midwest ┆ -89.0491 ┆ 42.9756   │
│ ALTE.COLUMBAL1 ┆ GEN       ┆ Midwest ┆ -89.4202 ┆ 43.4861   │
│ ALTE.COLUMBAL2 ┆ GEN       ┆ Midwest ┆ -89.4102 ┆ 43.4861   │
│ ALTE.EDGG5G5   ┆ GEN       ┆ Midwest ┆ -87.7062 ┆ 43.7158   │
└────────────────┴───────────┴─────────┴──────────┴───────────┘

In [6]:
import polars as pl

prices.filter(pl.col("location") == "MINN.HUB")

shape: (1, 6)
┌──────────┬───────────┬─────┬──────┬─────────────┬────────────────────────────────┐
│ location ┆ lmp       ┆ mcc ┆ mlc  ┆ status_code ┆ datetime                       │
│ ---      ┆ ---       ┆ --- ┆ ---  ┆ ---         ┆ ---                            │
│ str      ┆ f32       ┆ f32 ┆ f32  ┆ i16         ┆ datetime[μs, America/Chicago]  │
╞══════════╪═══════════╪═════╪══════╪═════════════╪════════════════════════════════╡
│ MINN.HUB ┆ 30.860001 ┆ 0.0 ┆ 0.74 ┆ 200         ┆ 2026-01-05 19:49:01.563255 CST │
└──────────┴───────────┴─────┴──────┴─────────────┴────────────────────────────────┘