In [2]:
from src.pricing import reload_prices_df

prices = reload_prices_df()
prices.head()

shape: (5, 6)
┌────────────────┬───────────┬───────┬───────┬─────────────┬────────────────────────────────┐
│ location       ┆ lmp       ┆ mcc   ┆ mlc   ┆ status_code ┆ datetime                       │
│ ---            ┆ ---       ┆ ---   ┆ ---   ┆ ---         ┆ ---                            │
│ str            ┆ f32       ┆ f32   ┆ f32   ┆ i16         ┆ datetime[μs, America/Chicago]  │
╞════════════════╪═══════════╪═══════╪═══════╪═════════════╪════════════════════════════════╡
│ AECI           ┆ 27.23     ┆ -3.38 ┆ -2.07 ┆ 200         ┆ 2026-01-05 13:51:34.461081 CST │
│ ALTE.1ROCKGEN  ┆ 31.870001 ┆ 0.57  ┆ -1.38 ┆ 200         ┆ 2026-01-05 13:51:34.461081 CST │
│ ALTE.COLUMBAL1 ┆ 33.139999 ┆ 0.8   ┆ -0.34 ┆ 200         ┆ 2026-01-05 13:51:34.461081 CST │
│ ALTE.COLUMBAL2 ┆ 33.009998 ┆ 0.8   ┆ -0.47 ┆ 200         ┆ 2026-01-05 13:51:34.461081 CST │
│ ALTE.EDGG5G5   ┆ 33.34     ┆ 0.75  ┆ -0.09 ┆ 200         ┆ 2026-01-05 13:51:34.461081 CST │
└────────────────┴───────────┴───────┴───────┴─────────────┴────────────────────────────────┘

In [3]:
from src.location import get_location_df

locations = get_location_df()
locations.head()

shape: (5, 5)
┌────────────────┬───────────┬─────────┬──────────┬───────────┐
│ location       ┆ node_type ┆ region  ┆ latitude ┆ longitude │
│ ---            ┆ ---       ┆ ---     ┆ ---      ┆ ---       │
│ str            ┆ str       ┆ str     ┆ f64      ┆ f64       │
╞════════════════╪═══════════╪═════════╪══════════╪═══════════╡
│ AECI           ┆ INT       ┆ Midwest ┆ -92.6024 ┆ 39.4467   │
│ ALTE.1ROCKGEN  ┆ GEN       ┆ Midwest ┆ -89.0491 ┆ 42.9756   │
│ ALTE.COLUMBAL1 ┆ GEN       ┆ Midwest ┆ -89.4202 ┆ 43.4861   │
│ ALTE.COLUMBAL2 ┆ GEN       ┆ Midwest ┆ -89.4102 ┆ 43.4861   │
│ ALTE.EDGG5G5   ┆ GEN       ┆ Midwest ┆ -87.7062 ┆ 43.7158   │
└────────────────┴───────────┴─────────┴──────────┴───────────┘