In [1]:
from src.pricing import reload_prices_df

prices = reload_prices_df()
prices.head()

shape: (5, 6)
┌────────────────┬───────────┬───────┬───────┬─────────────┬───────────────────────────────┐
│ location       ┆ lmp       ┆ mcc   ┆ mlc   ┆ status_code ┆ datetime                      │
│ ---            ┆ ---       ┆ ---   ┆ ---   ┆ ---         ┆ ---                           │
│ str            ┆ f32       ┆ f32   ┆ f32   ┆ i16         ┆ datetime[ms, America/Chicago] │
╞════════════════╪═══════════╪═══════╪═══════╪═════════════╪═══════════════════════════════╡
│ AECI           ┆ 27.91     ┆ -2.41 ┆ -2.0  ┆ 200         ┆ 2026-01-05 07:33:32.802 CST   │
│ ALTE.1ROCKGEN  ┆ 31.110001 ┆ 0.21  ┆ -1.42 ┆ 200         ┆ 2026-01-05 07:33:32.802 CST   │
│ ALTE.COLUMBAL1 ┆ 32.169998 ┆ 0.29  ┆ -0.44 ┆ 200         ┆ 2026-01-05 07:33:32.802 CST   │
│ ALTE.COLUMBAL2 ┆ 32.029999 ┆ 0.29  ┆ -0.58 ┆ 200         ┆ 2026-01-05 07:33:32.802 CST   │
│ ALTE.EDGG5G5   ┆ 32.41     ┆ 0.27  ┆ -0.18 ┆ 200         ┆ 2026-01-05 07:33:32.802 CST   │
└────────────────┴───────────┴───────┴───────┴─────────────┴───────────────────────────────┘

In [2]:
from src.location import get_location_df

locations = get_location_df()
locations.head()

shape: (5, 5)
┌────────────────┬───────────┬─────────┬──────────┬───────────┐
│ location       ┆ node_type ┆ region  ┆ latitude ┆ longitude │
│ ---            ┆ ---       ┆ ---     ┆ ---      ┆ ---       │
│ str            ┆ str       ┆ str     ┆ f64      ┆ f64       │
╞════════════════╪═══════════╪═════════╪══════════╪═══════════╡
│ AECI           ┆ INT       ┆ Midwest ┆ -92.6024 ┆ 39.4467   │
│ ALTE.1ROCKGEN  ┆ GEN       ┆ Midwest ┆ -89.0491 ┆ 42.9756   │
│ ALTE.COLUMBAL1 ┆ GEN       ┆ Midwest ┆ -89.4202 ┆ 43.4861   │
│ ALTE.COLUMBAL2 ┆ GEN       ┆ Midwest ┆ -89.4102 ┆ 43.4861   │
│ ALTE.EDGG5G5   ┆ GEN       ┆ Midwest ┆ -87.7062 ┆ 43.7158   │
└────────────────┴───────────┴─────────┴──────────┴───────────┘

In [ ]:
import zoneinfo
zoneinfo.available_timezones()